FROM node as build-stage
WORKDIR /app
COPY ./site/package*.json ./
RUN yarn install
COPY ./site/ .
RUN yarn run build
RUN yarn run generate

FROM caddy:alpine
WORKDIR /app
COPY ./Caddyfile /etc/caddy/Caddyfile
COPY site /srv
COPY --from=build-stage /app/dist /srv
#TEST