# Use root/example as user/password credentials
version: "3.1"
services:
  # Vue Frontend
  portfolio-test-build:
    image: portfolio:latest
    container_name: portfolio
    networks:
      - web
    build:
      context: ./
      dockerfile: DockerFile
    restart: always
networks:
  web:
    external: true
