# Use root/example as user/password credentials
version: "3.1"
services:
  # Vue Frontend
  portfolio-test-build:
    image: nuxt-portfolio:dev
    build:
      context: ./
      dockerfile: DockerFile
    restart: always
    ports:
      - 9959:80
