name: remote ssh command
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            mkdir ~/docker/portfolio -p
            cd ~/docker/portfolio -p
            git clone https://github.com/hay-kot/portfolio
            docker build -t portfolio .
            docker run -d portfolio
